"""
Generate a standalone Python script that re-runs a chat's queries offline, without Datasquint or the AI.

The script rebuilds each attached CSV/TSV/Excel table from the original file exactly the way Datasquint
loaded it (same DuckDB options, same sheet conversion, same blocks for sheets holding several tables),
connects to PostgreSQL for database queries, runs every query and saves each result as a CSV.
"""
import datetime
import pprint
import re

from version import __version__ as VERSION


def _slug(s, n=40):
    return re.sub(r"[^a-z0-9]+", "_", (s or "").lower()).strip("_")[:n] or "query"


def _py_str(sql):
    """A readable Python literal for SQL: raw triple-quoted when safe, repr() otherwise."""
    if "'''" not in sql and not sql.endswith("\\") and "\r" not in sql:
        return "r'''" + sql + "'''"
    return repr(sql)


def _doc(s):
    """Text that is safe inside the script's docstring."""
    return str(s).replace(chr(92), "/").replace(chr(34) * 3, chr(39) * 3).replace(chr(13), " ")


def _env_prefix(name):
    return "DS_" + re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_") + "_"


def build(title, queries, file_tables, databases):
    """queries: [{"title", "sql", "source"}] (source = "files" or a database name)
    file_tables: [{"name", "file", "sheet", "load"}] for the tables the file queries use
    databases: {name: {"host", "port", "dbname", "user", "sslmode", "ssh"}}
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    files = sorted({t["file"] for t in file_tables})
    approx = [t["name"] for t in file_tables if t.get("approximate")]
    lines_q = "\n".join(f"  {i}. {_doc(q['title'])}  [{_doc(q['source'])}]" for i, q in enumerate(queries, 1))
    title = _doc(title).replace("\n", " ")
    needs = ["duckdb"] if file_tables else []
    if any(t["load"]["kind"] == "sheet" for t in file_tables):
        needs.append("openpyxl")
    if databases:
        needs.append('"psycopg[binary]"')
    db_notes = ""
    for name, d in databases.items():
        p = _env_prefix(name)
        db_notes += (f"\nDatabase '{_doc(name)}': {d.get('user') or '?'}@{d.get('host')}:{d.get('port')}/{d.get('dbname')}\n"
                     f"  Password: set {p}PASSWORD (or PGPASSWORD), or type it when asked.\n"
                     f"  Override host/port/user/dbname with {p}HOST, {p}PORT, {p}USER, {p}DBNAME.\n")
        if d.get("ssh"):
            s = d["ssh"]
            db_notes += (f"  Reached through SSH ({s.get('user') or '?'}@{s.get('host')}:{s.get('port') or 22}). "
                         f"Open a tunnel first, e.g.\n"
                         f"    ssh -N -L 15432:{d.get('host')}:{d.get('port')} {s.get('user') or 'user'}@{s.get('host')} -p {s.get('port') or 22}\n"
                         f"  then run with {p}HOST=localhost {p}PORT=15432\n")

    q_literal = "[\n" + "".join(
        f"    {{\"title\": {q['title']!r},\n     \"source\": {q['source']!r},\n     \"sql\": {_py_str(q['sql'])}}},\n"
        for q in queries) + "]"
    head = f'''#!/usr/bin/env python3
"""
{title}

Generated by Datasquint {VERSION} on {now}. Re-runs {len(queries)} quer{"y" if len(queries) == 1 else "ies"} from the chat,
offline, and saves each result as a CSV:
{lines_q}

Install:  pip install {" ".join(needs) or "(nothing extra)"}
{"Data files: put these next to this script, or pass --data FOLDER:" + chr(10) + chr(10).join("  " + f for f in files) + chr(10) if files else ""}{db_notes}
Run:      python {_slug(title)}.py [--data FOLDER] [--out FOLDER] [--only N] [--show 20]
{("Note: " + ", ".join(approx) + " came from uploads made before Datasquint 2.2.0; they are rebuilt" + chr(10) + "the standard way, which matches unless the file needed special handling." + chr(10)) if approx else ""}"""'''

    body = r'''
import argparse
import csv
import datetime
import os
import re
import sys
import tempfile

FILE_TABLES = __FILE_TABLES__

DATABASES = __DATABASES__

QUERIES = __QUERIES__

CSV_OPTS = "normalize_names=true, sample_size=-1, null_padding=true"


# ------------------------------------------------------------------ files -> DuckDB tables
def xcell(v):
    """An Excel value as CSV text, the way Datasquint converts it (so column types match)."""
    if v is None:
        return ""
    if isinstance(v, datetime.datetime):
        return v.isoformat(sep=" ")
    if isinstance(v, (datetime.date, datetime.time)):
        return v.isoformat()
    if isinstance(v, datetime.timedelta):
        return str(v)
    if isinstance(v, float) and v.is_integer() and abs(v) < 2 ** 53:
        return int(v)
    return v


def blank(cells):
    return not any(v is not None and str(v).strip() != "" for v in cells)


def sheet_rows(path, sheet):
    """(Excel row number, values) for every row of a sheet."""
    from openpyxl import load_workbook
    wb = load_workbook(path, read_only=True, data_only=True)
    try:
        if sheet not in wb.sheetnames:
            sys.exit(f"Sheet '{sheet}' not found in {path}. Sheets: {', '.join(wb.sheetnames)}")
        for r, row in enumerate(wb[sheet].iter_rows(values_only=True), start=1):
            yield r, list(row)
    finally:
        wb.close()


def csv_records(path, encoding, delim):
    with open(path, encoding=encoding or "utf-8-sig", newline="") as fh:
        yield from enumerate(csv.reader(fh, delimiter=delim or ","))


def write_csv(path, rows):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        csv.writer(fh).writerows(rows)


def block_rows(load, path):
    """Rows of one table found inside a sheet/CSV holding several tables."""
    for a, b, lo, hi, skip in load["parts"]:
        skip = set(skip)
        width = hi - lo + 1
        if load["kind"] == "sheet":
            src = ((r, row[lo - 1:hi]) for r, row in sheet_rows(path, load["sheet"]) if a <= r <= b)
        else:
            src = ((i, row[lo:hi + 1]) for i, row in csv_records(path, load.get("encoding"), load.get("delim")) if a <= i <= b)
        for i, cells in src:
            if i in skip or blank(cells):
                continue
            yield ([xcell(v) for v in cells] + [""] * width)[:width]


def load_table(con, t, folder, tmp):
    import duckdb
    path = os.path.join(folder, t["file"])
    if not os.path.exists(path):
        sys.exit(f"Missing data file: {path}\nPut the original '{t['file']}' there, or pass --data FOLDER.")
    load, name = t["load"], '"' + t["name"].replace('"', '""') + '"'
    if load.get("parts"):
        out = os.path.join(tmp, t["name"] + ".csv")
        write_csv(out, block_rows(load, path))
        header = "true" if load.get("header") else "auto"
        con.execute(f"CREATE TABLE {name} AS SELECT * FROM read_csv(?, {CSV_OPTS}, delim=',', header={header})", [out])
    elif load["kind"] == "sheet":
        off, width = load.get("col_offset", 0), load.get("width")
        out = os.path.join(tmp, t["name"] + ".csv")
        write_csv(out, ([xcell(v) for v in (row[off:off + width] if width else row[off:])]
                        for _, row in sheet_rows(path, load["sheet"]) if not blank(row)))
        con.execute(f"CREATE TABLE {name} AS SELECT * FROM read_csv(?, {CSV_OPTS})", [out])
    else:
        delim = ", delim='\\t'" if load.get("delim") == "\t" else ""
        try:
            con.execute(f"CREATE TABLE {name} AS SELECT * FROM read_csv(?, {CSV_OPTS}{delim})", [path])
        except duckdb.Error:   # not UTF-8 (e.g. saved by Excel as Windows-1252): convert, then load
            out = os.path.join(tmp, t["name"] + "_utf8.csv")
            with open(path, encoding=load.get("encoding") or "latin-1", newline="") as fi, \
                    open(out, "w", encoding="utf-8", newline="") as fo:
                fo.write(fi.read())
            con.execute(f"CREATE TABLE {name} AS SELECT * FROM read_csv(?, {CSV_OPTS}{delim})", [out])
    n = con.execute(f"SELECT count(*) FROM {name}").fetchone()[0]
    print(f"  loaded {t['name']}: {n:,} rows from {t['file']}" + (f" (sheet {t['sheet']})" if t.get("sheet") else ""))


def files_connection(folder, needed):
    try:
        import duckdb
    except ImportError:
        sys.exit("This script needs DuckDB for the attached files: pip install duckdb")
    con = duckdb.connect()
    tmp = tempfile.mkdtemp(prefix="datasquint_")
    for t in FILE_TABLES:
        if t["name"] in needed:
            load_table(con, t, folder, tmp)
    return con


# ------------------------------------------------------------------ databases
def db_connection(name):
    try:
        import psycopg
    except ImportError:
        sys.exit('This script needs psycopg for PostgreSQL: pip install "psycopg[binary]"')
    d = DATABASES[name]
    p = "DS_" + re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_") + "_"
    pg = {"HOST": "PGHOST", "PORT": "PGPORT", "DBNAME": "PGDATABASE", "USER": "PGUSER"}
    env = lambda key, default: os.getenv(p + key) or os.getenv(pg[key]) or default
    password = os.getenv(p + "PASSWORD") or os.getenv("PGPASSWORD")
    if password is None:
        import getpass
        password = getpass.getpass(f"Password for {d.get('user')}@{d.get('host')} ({name}): ")
    conn = psycopg.connect(host=env("HOST", d.get("host")), port=env("PORT", d.get("port")),
                           dbname=env("DBNAME", d.get("dbname")), user=env("USER", d.get("user")),
                           password=password, sslmode=d.get("sslmode") or "prefer", connect_timeout=15)
    conn.read_only = True   # this script only reads
    return conn


# ------------------------------------------------------------------ run
def show(columns, rows, limit):
    if not columns or limit <= 0:
        return
    rows = [["" if v is None else str(v) for v in r] for r in rows[:limit]]
    widths = [min(30, max([len(c)] + [len(r[i]) for r in rows])) for i, c in enumerate(columns)]
    line = lambda cells: "  " + " | ".join(str(c)[:w].ljust(w) for c, w in zip(cells, widths))
    print(line(columns))
    print("  " + "-+-".join("-" * w for w in widths))
    for r in rows:
        print(line(r))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--data", default=here, help="folder with the original data files (default: this script's folder)")
    ap.add_argument("--out", default=os.path.join(here, "output"), help="folder for result CSVs (default: ./output)")
    ap.add_argument("--only", type=int, help="run only query number N")
    ap.add_argument("--show", type=int, default=10, help="rows to print per result (default 10)")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    todo = [(i, q) for i, q in enumerate(QUERIES, 1) if not args.only or i == args.only]
    file_sql = " ".join(q["sql"] for _, q in todo if q["source"] == "files").lower()
    needed = {t["name"] for t in FILE_TABLES if re.search(r"\b" + re.escape(t["name"].lower()) + r"\b", file_sql)}
    files_con = files_connection(args.data, needed) if needed else None
    db_cons = {}
    for i, q in todo:
        print(f"\n[{i}] {q['title']}  ({q['source']})")
        if q["source"] == "files":
            cur = files_con.execute(q["sql"])
            columns = [d[0] for d in cur.description] if cur.description else []
            rows = cur.fetchall() if columns else []
        else:
            if q["source"] not in db_cons:
                db_cons[q["source"]] = db_connection(q["source"])
            with db_cons[q["source"]].cursor() as cur:
                cur.execute(q["sql"])
                columns = [d.name for d in cur.description] if cur.description else []
                rows = cur.fetchall() if columns else []
        out = os.path.join(args.out, f"{i:02d}_{re.sub(r'[^a-z0-9]+', '_', q['title'].lower()).strip('_')[:40] or 'result'}.csv")
        with open(out, "w", encoding="utf-8-sig", newline="") as fh:   # with BOM so Excel shows accents
            w = csv.writer(fh)
            w.writerow(columns)
            w.writerows(rows)
        show(columns, rows, args.show)
        print(f"  {len(rows):,} rows -> {out}")
    for c in db_cons.values():
        c.close()


if __name__ == "__main__":
    main()
'''
    tables_literal = pprint.pformat([{k: t[k] for k in ("name", "file", "sheet", "load")} for t in file_tables],
                                    indent=1, width=110, sort_dicts=False)
    dbs_literal = pprint.pformat(databases, indent=1, width=110, sort_dicts=False)
    body = (body.replace("__FILE_TABLES__", tables_literal)
                .replace("__DATABASES__", dbs_literal)
                .replace("__QUERIES__", q_literal))
    return head + "\n" + body
